// AngularClient/angular-user-client/src/app/user/user.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { User } from "../models/User";
import { Gender } from "../models/Gender";
import { isNumber } from "util";
import { UserService } from "../services/user/user.service";
import { ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-user',
  templateUrl: './user.component.html',
  styleUrls: ['./user.component.sass']
})
export class UserComponent implements OnInit {

  post: any;
  keys: Array<string>;
  header: string;
  isEdit: boolean = false;
  private sub: any;
  @Input() user: User;

  constructor(private _userService: UserService, private route: ActivatedRoute) {
  }

  ngOnInit() {
    this.user = new User();
    // Get values from enum
    this.keys = Object.keys(Gender).map(k => Gender[k]).filter(v => typeof v === "string") as string[];

    this.sub = this.route.params.subscribe(params => {
      this.header = "Add";
      if (params['id']) {
        this._userService.getUserById(params['id']).subscribe(user => {
          this.user = user;
          this.isEdit = true;
          this.header = "Edit";
        });
      }
   });
  }

  onAddUser() : void {
    if (this.isEdit){
      this._userService.putUser(this.user);
    }else {
      console.log(this.user);
      this._userService.addUser(this.user);
    }

  }

}

<!-- <form [formGroup]="myForm" novalidate (ngSubmit)="onAddUser(myForm.value, myForm.valid)">
    <div>
        <label>Name</label>
        <input type="text" formControlName="name">
        <small [hidden]="myForm.controls.name.valid || (myForm.controls.name.pristine && !submitted) || !myForm.controls.name.touched">
            Name is required.
        </small>
    </div>

    <div>
        <label>Surname</label>
        <input type="text" formControlName="surname">
        <small [hidden]="myForm.controls.surname.valid || (myForm.controls.surname.pristine && !submitted) || !myForm.controls.surname.touched">
            Surname is required.
        </small>
    </div>

    <div>
        <label>Email</label>
        <input type="text" formControlName="email">
        <small [hidden]="myForm.controls.email.valid || (myForm.controls.email.pristine && !submitted) || !myForm.controls.email.touched">
            Email is not valid.
        </small>
    </div>

    <div>
        <label>Gender</label>
        <select formControlName="gender" ng-init="keys[0]">
            <option *ngFor="let key of keys" [value]="key" [label]="key"></option>
        </select>
        <small [hidden]="myForm.controls.gender.valid || (myForm.controls.gender.pristine && !submitted)">
            Gender is required.
        </small>
    </div>

    <button type="submit" [disabled]="!myForm.valid">Submit</button>

</form> -->

<form class="form-horizontal"  [formGroup]="myForm" novalidate (ngSubmit)="onAddUser(myForm.value, true)">
    <fieldset>

        <!-- Form Name -->
        <legend>{{formHeader}} user</legend>

        <!-- Name input-->
        <div class="form-group">
            <label class="col-md-4 control-label" for="name"></label>
            <div class="col-md-4">
                <input id="name" value="{{user.Name}}" name="name" type="text" placeholder="Name" class="form-control input-md" required="">

            </div>
        </div>

        <!-- Surname input-->
        <div class="form-group">
            <label class="col-md-4 control-label" for="surname"></label>
            <div class="col-md-4">
                <input id="surname" value="{{user.Surname}}" name="surname" type="text" placeholder="Surname" class="form-control input-md" required="">

            </div>
        </div>

        <!-- Email input-->
        <div class="form-group">
            <label class="col-md-4 control-label" for="email"></label>
            <div class="col-md-4">
                <input id="email" value="{{user.Email}}" name="email" type="text" placeholder="Email" class="form-control input-md" required="">

            </div>
        </div>

        <!-- Select Basic -->
        <div class="form-group">
            <label class="col-md-4 control-label" for="gender"></label>
            <div class="col-md-4">
                <select id="gender" name="gender" class="form-control">
                    <option *ngFor="let key of keys" [value]="key" [label]="key"></option>
                </select>
            </div>
        </div>

        <!-- Button -->
        <div class="form-group">
            <label class="col-md-4 control-label" for="Submit"></label>
            <div class="col-md-4">
                <button id="Submit" name="Submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </fieldset>
</form>

// ReactClient/react-user-client/src/components/User.js
import React from 'react';
import PropTypes from 'prop-types';
import { Gender } from '../models/Gender';
import './User.css';
let api = require('../utils/api');

export class User extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            mode: this.getMode(),
            user: this.getUser(),
            genderKeys: this.getGenderKeys()
        };
    }

    getGenderKeys() {
        return Object.keys(Gender).map(k => Gender[k]).filter(v => typeof v === "string");
    }

    getMode() {
        // Init form legend header based on parameter
        let mode = "Add";
        try {
            if ('isUserEdit' in this.props.location.state) {
                mode = "Edit";
            }
        } 
        catch(e) {
            console.log("Mode is not initialized");
        }

        return mode;
    }

    getUser() {
        let user = {};
        try {
            if ('user' in this.props.location.state) {
                user = this.props.location.state.user;
            }
        } 
        catch(e) {
            console.log("User is not initialized");
        }

        return user;
    }

    formGenderSelection() {
        return (
            <select id="gender" name="gender" className="form-control input-md" ref="gender">
               { 
                    this.state.genderKeys.map(function (obj, i) {
                        return <option defaultValue={i} key={i}>{obj}</option>
                    })
               }
            </select>
        );
    }

    handleSubmit(e) {
        e.preventDefault();

        let newUser = {
            id: this.state.user.Id,
            name: this.refs.name.value,
            surname: this.refs.surname.value,
            email: this.refs.email.value,
            gender: this.refs.gender.value
        };

        if (this.state.mode === "Add") {
            api.addUser(newUser)
                .then(() => {
                    console.log("Add user");
                });
        } else {
            api.putUser(newUser, this.state.user.Id)
                .then(() => {
                    console.log("Update user");
                });
        }
    }

    render() {
        return (
            <form onSubmit={this.handleSubmit.bind(this)} className="form-horizontal">
                <fieldset>
                    <legend>{this.state.mode} User</legend>
                    
                    <div className="inputWrapper">
                        <div className="form-group">
                            <input id="name" name="name" type="text" 
                                placeholder="Name" className="form-control input-md" required=""
                                ref="name"
                                defaultValue={this.state.user.Name}/>
                        </div>
                    </div>
                    
                    <div className="inputWrapper">
                        <div className="form-group">
                            <input id="surname" name="surname" type="text" 
                                placeholder="Surname" className="form-control input-md" required=""
                                ref="surname"
                                defaultValue={this.state.user.Surname}/>
                        </div>
                    </div>
                    
                    <div className="inputWrapper">
                        <div className="form-group">
                            <input id="email" name="email" type="text" 
                                placeholder="Email" className="form-control input-md" required=""
                                ref="email"
                                defaultValue={this.state.user.Email}/>
                        </div>
                    </div>
                    
                    <div className="inputWrapper">
                        <div className="form-group">
                            {this.formGenderSelection()}
                        </div>
                    </div>
                    
                    <div className="inputWrapper">
                        <div className="form-group">
                            <button id="Submit" name="Submit" className="btn btn-primary">Submit</button>
                        </div>
                    </div>
                </fieldset>
            </form>
        );
    }
}

User.propTypes = {
    user: PropTypes.object,
    isUserEdit: PropTypes.bool
};
